### ISSUE TITLE
[Info] retrofit2 supports @RequestInterceptor for each method

### ISSUE THREAD

**Issue by yongjhih** [Unic8/retroauth#7]
See Also:

* https://github.com/yongjhih/retrofit/blob/master/retrofit2-github/src/main/java/com/github/retrofit2/GitHub.java#L56
* https://github.com/yongjhih/retrofit/blob/master/retrofit2-github/src/main/java/com/github/retrofit2/GitHubAuthInterceptor.java

**Comment by Unic8** [comment]
Please only post issues when there is an actual issue with the library, not when you want to promote your own library.
